# Site settings
version: 0.0.1

title: Блогушка
tagline: Fight for your dreams!
about: Коротко о Ди
email: ndilya@mail.ru
description: >
  Несколько слов о Ди

# About/contact
author:
  name: Назарова Диля
  email: ndilya@mail.ru
  image: "/assets/img/di.jpg"
  url:  http://melandi.github.io

social:
  - icon: vk
    url: http://vk.com/dilyanazarova

  - icon: instagram
    url: https://www.instagram.com/nazarova.di

  - icon: github
    url: https://github.com/melandi

baseurl: ""
url: "http://melandi.github.io"
timezone: Europe/Moscow

# Conversion
encoding: UTF-8
markdown: kramdown
markdown_ext: markdown,md

# Outputting
paginate: 4
permalink: "/:categories/:title.html"
paginate_path: "/page/:num"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      categories: "post"

gems:
  - jemoji
  - jekyll-gist
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-redirect-from

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: compressed
